server:
  host: "0.0.0.0"
  port: 8000

ocr:
  device: "gpu:0"
  lang: "ch"

  text_detection_model_name: "PP-OCRv5_mobile_det"
  text_detection_model_dir: "D:/PaddleOCR/deploy_models/det_final_infer"

  text_recognition_model_name: "PP-OCRv5_mobile_rec"
  text_recognition_model_dir: "D:/PaddleOCR/deploy_models/rec_round6_infer"

  text_rec_input_shape: [3, 48, 320]

  use_doc_orientation_classify: false
  use_doc_unwarping: false
  use_textline_orientation: false

paths:
  upload_dir: "./uploads"
  result_dir: "./results"